
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: dic_task_contact_development

test:
  <<: *default
  database: dic_task_contact_test

production:
  <<: *default
  database: dic_task_contact_production
  username: dic_task_contact
  password: <%= ENV['DIC_TASK_CONTACT_DATABASE_PASSWORD'] %>
