# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82fc1acb6853127380e154784641683f97315631371b5309c8bc2965d5c93d4ae6a0b4203d2cffc475f160965f034a23ce8a03acb37e39b7de593b702de06db0

test:
  secret_key_base: 87e64d26c69a37ce141b8c4135757b884d7a618f78a170df64166e1e794379e9e8acb7222fe24c0df86c2486c089c74db51b8eaf7b44a34440361c3477356115

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
